import torch
import torch.nn as nn
import math
import einops
import torch.utils.checkpoint
import torch.nn.functional as F
import numpy as np
import math
from math import sqrt, ceil
from einops import rearrange, repeat

class Mlp(nn.Module):
    def __init__(self, in_features, hidden_features=None, out_features=None, act_layer=nn.GELU, drop=0.):
        super().__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        self.fc1 = nn.Linear(in_features, hidden_features)
        self.act = act_layer()
        self.fc2 = nn.Linear(hidden_features, out_features)
        self.drop = nn.Dropout(drop)

    def forward(self, x):
        x = self.fc1(x)
        x = self.act(x)
        x = self.drop(x)
        x = self.fc2(x)
        x = self.drop(x)
        return x
    

import math
import warnings
def exists(x):
    return x is not None

def default(val, d):
    if exists(val):
        return val
    return d() if callable(d) else d

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a -
                       mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (torch.Tensor, float, float, float, float) -> torch.Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)

if hasattr(torch.nn.functional, 'scaled_dot_product_attention'):
    ATTENTION_MODE = 'flash'
else:
    try:
        import xformers
        import xformers.ops
        ATTENTION_MODE = 'xformers'
    except:
        ATTENTION_MODE = 'math'
# print(f'attention mode is {ATTENTION_MODE}')


def timestep_embedding(timesteps, dim, max_period=10000):
    """
    Create sinusoidal timestep embeddings.

    :param timesteps: a 1-D Tensor of N indices, one per batch element.
                      These may be fractional.
    :param dim: the dimension of the output.
    :param max_period: controls the minimum frequency of the embeddings.
    :return: an [N x dim] Tensor of positional embeddings.
    """
    half = dim // 2
    freqs = torch.exp(
        -math.log(max_period) * torch.arange(start=0, end=half, dtype=torch.float32) / half
    ).to(device=timesteps.device)
    args = timesteps[:, None].float() * freqs[None]
    embedding = torch.cat([torch.cos(args), torch.sin(args)], dim=-1)
    if dim % 2:
        embedding = torch.cat([embedding, torch.zeros_like(embedding[:, :1])], dim=-1)
    return embedding


class MPSiLU(nn.Module):
    def forward(self, x):
        return F.silu(x) / 0.596


class UNet1D(nn.Module):
    """
    适用于 1D 特征的 UNet 模型 (基于 CLUDI 的 UViTLin 修改)
    用于处理经过 ViT 提取后的 1D 特征进行扩散/聚类
    """
    def __init__(self, 
                 in_dim=384,          # 输入特征维度 (ViT输出维度)
                 embed_dim=384,       # 内部嵌入维度
                 n_clusters=10,       # 聚类数
                 mlp_time_embed=True, # 是否使用 MLP 处理时间嵌入
                 self_condition=True, # 是否使用自条件
                 dropout=0.15):
        super().__init__()
        self.in_dim = in_dim
        self.embed_dim = embed_dim
        self.n_clusters = n_clusters
        self.self_condition = self_condition
        
        # 时间嵌入维度
        self.time_embed_dim = embed_dim
        
        # 时间嵌入层
        self.time_embed = nn.Sequential(
            nn.Linear(embed_dim, 4 * embed_dim),
            MPSiLU(),
            nn.Linear(4 * embed_dim, embed_dim),
        ) if mlp_time_embed else nn.Identity()
        
        # 输入投影层
        # 如果使用自条件，输入维度会增加 (通常是拼接了之前的预测或条件)
        # 这里假设自条件是拼接在特征维度上
        input_dim = in_dim * 2 if self_condition else in_dim
        
        self.input_proj = nn.Sequential(
            nn.Linear(input_dim, embed_dim),
            MPSiLU(),
            nn.Linear(embed_dim, embed_dim),
            nn.LayerNorm(embed_dim),
        )
        
        self.dropout = nn.Dropout(dropout)
        
        # 主干网络 (ResNet-like MLP blocks)
        self.network = nn.Sequential(
            # Block 1
            nn.Linear(embed_dim, embed_dim),
            MPSiLU(),
            nn.Dropout(dropout),
            
            # Block 2
            nn.Linear(embed_dim, embed_dim),
            MPSiLU(),
            nn.Dropout(dropout),
            
            # Block 3
            nn.Linear(embed_dim, embed_dim),
            MPSiLU(),
            nn.Dropout(dropout),
            
            # Block 4
            nn.Linear(embed_dim, embed_dim),
            MPSiLU(),
            nn.Dropout(dropout),
        )
        
        # 输出层
        self.norm = nn.LayerNorm(embed_dim)
        
        # 预测噪声/特征的输出头
        self.output_head = nn.Sequential(
            nn.Linear(embed_dim, embed_dim),
            MPSiLU(),
            nn.Linear(embed_dim, in_dim) # 输出回原始维度
        )
        
        # 聚类相关的层 (可选，如果需要直接预测聚类分布)
        self.cluster_head = nn.Sequential(
            nn.Linear(embed_dim, embed_dim),
            MPSiLU(),
            nn.Linear(embed_dim, n_clusters)
        )
        
        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def forward(self, x, timesteps, self_cond=None, return_z=False):
        """
        Args:
            x: 输入特征 [B, in_dim]
            timesteps: 时间步 [B]
            self_cond: 自条件 [B, in_dim] (可选)
            return_z: 是否返回中间特征 z
        """
        # 1. 处理自条件
        if self.self_condition:
            if self_cond is None:
                self_cond = torch.zeros_like(x)
            x_in = torch.cat((x, self_cond), dim=-1)
        else:
            x_in = x
            
        # 2. 输入投影
        h = self.input_proj(x_in)
        h = self.dropout(h)
        
        # 3. 加入时间嵌入
        t_emb = timestep_embedding(timesteps, self.time_embed_dim)
        t_emb = self.time_embed(t_emb)
        h = h + t_emb
        
        # 4. 主干网络
        z = self.network(h)
        z = self.norm(z)
        
        # 5. 输出
        out = self.output_head(z)
        
        if return_z:
            return out, z
        return out

